name: flutter_native_splash
description: Generates native code to customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more.
version: 0.2.10
homepage: https://github.com/jonbhanson/flutter_native_splash

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  yaml: ^2.2.1
  image: ^3.0.0-nullsafety.0
  xml: ^5.0.0-nullsafety.1

dev_dependencies:
  pedantic: ^1.9.2
